name: First Workflow
on: workflow_dispatch # manually triggered
jobs:
  first-job:
    runs-on: ubuntu-latest # build agent
    steps: 
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done -bye!"
